### ISSUE TITLE
Odd error from actix-rt:worker on web-starter

### ISSUE THREAD

**Issue by JulianRuiseco** [secretkeysio/jelly-actix-web-starter#16]
thread 'actix-rt:worker:1' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-3.3.2\src\server.rs:282:36
stack backtrace:

I am using windows, with the following .env

I'm happy to keep digging, but I wanted to know if anyone has hit this previously.

```
BIND_TO="127.0.0.1:17001"
DOMAIN="http://127.0.0.1:17001"
SESSIONID_DOMAIN="https://www.example.com:17001"
DATABASE_URL="postgresql://postgres:password@localhost:5432/fse"
SECRET_KEY="testymctesterson123"
POSTMARK_API_KEY=""
TEMPLATES_GLOB="templates/**/*"
STATIC_ROOT="static"
RUST_BACKTRACE=full
RUST_LOG="info,actix_web=trace,background_jobs_core=debug"
```

```
thread 'actix-rt:worker:3' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-3.3.2\src\server.rs:282:36
stack backtrace:
   0:     0x7ff6e407374e - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6e407374e - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6e407374e - std::sys_common::backtrace::_print_fmt
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff6e407374e - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff6e408a4cc - core::fmt::write
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\core\src\fmt\mod.rs:1094
   5:     0x7ff6e406be38 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\io\mod.rs:1584
   6:     0x7ff6e4076202 - std::sys_common::backtrace::_print
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff6e4076202 - std::sys_common::backtrace::print
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff6e4076202 - std::panicking::default_hook::{{closure}}
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\panicking.rs:208
   9:     0x7ff6e4075cf4 - std::panicking::default_hook
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\panicking.rs:225
  10:     0x7ff6e4076833 - std::panicking::rust_panic_with_hook
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\panicking.rs:591
  11:     0x7ff6e4076451 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\panicking.rs:497
  12:     0x7ff6e407409f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff6e40763a9 - std::panicking::begin_panic_handler
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\panicking.rs:493
  14:     0x7ff6e40f3f20 - core::panicking::panic_fmt
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\core\src\panicking.rs:92
  15:     0x7ff6e40f4033 - core::result::unwrap_failed
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\core\src\result.rs:1355
  16:     0x7ff6e2f3bc5d - core::result::Result<std::sync::mutex::MutexGuard<actix_web::server::Config>, std::sync::poison::PoisonError<std::sync::mutex::MutexGuard<actix_web::server::Config>>>::unwrap<std::sync::mutex::MutexGuard<actix_web::server::Config>,std::sync::poison::Poiso
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:1037
  17:     0x7ff6e2f00b01 - actix_web::server::{{impl}}::listen::{{closure}}<closure-0,actix_web::app::App<actix_service::transform::ApplyTransform<actix_session::cookie::CookieSession, actix_service::transform::ApplyTransform<actix_web::middleware::logger::Logger, actix_web::app_se
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-3.3.2\src\server.rs:282
  18:     0x7ff6e2eff3ae - actix_server::service::{{impl}}::create<closure-0,actix_service::pipeline::PipelineFactory<actix_service::and_then::AndThenServiceFactory<actix_service::fn_service::FnServiceFactory<closure-0, futures_util::future::ready::Ready<core::result::Result<tuple<
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-server-1.0.4\src\service.rs:183
  19:     0x7ff6e2efe85d - actix_server::service::{{impl}}::create<closure-0,tokio::net::tcp::stream::TcpStream>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-server-1.0.4\src\service.rs:148
  20:     0x7ff6e39512f5 - actix_server::service::{{impl}}::create
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-server-1.0.4\src\service.rs:170
  21:     0x7ff6e3978604 - actix_server::worker::{{impl}}::start::{{closure}}
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-server-1.0.4\src\worker.rs:189
  22:     0x7ff6e3958449 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
  23:     0x7ff6e393dc2c - core::future::future::{{impl}}::poll<alloc::boxed::Box<Future, alloc::alloc::Global>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\future.rs:120
  24:     0x7ff6e3f40b08 - alloc::boxed::{{impl}}::poll<Future,alloc::alloc::Global>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1711
  25:     0x7ff6e3f189c6 - tokio::runtime::task::core::{{impl}}::poll::{{closure}}<alloc::boxed::Box<Future, alloc::alloc::Global>,alloc::sync::Arc<tokio::task::local::Shared>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\core.rs:173
  26:     0x7ff6e3f116a2 - tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<alloc::boxed::Box<Future, alloc::alloc::Global>>>::with_mut<tokio::runtime::task::core::Stage<alloc::boxed::Box<Future, alloc::alloc::Global>>,core::task::poll::Poll<tuple<>>,clos
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\loom\std\unsafe_cell.rs:14
  27:     0x7ff6e3f18323 - tokio::runtime::task::core::Core<alloc::boxed::Box<Future, alloc::alloc::Global>, alloc::sync::Arc<tokio::task::local::Shared>>::poll<alloc::boxed::Box<Future, alloc::alloc::Global>,alloc::sync::Arc<tokio::task::local::Shared>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\core.rs:158
  28:     0x7ff6e3f3d97f - tokio::runtime::task::harness::{{impl}}::poll::{{closure}}<alloc::boxed::Box<Future, alloc::alloc::Global>,alloc::sync::Arc<tokio::task::local::Shared>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\harness.rs:107
  29:     0x7ff6e3f130da - core::ops::function::FnOnce::call_once<closure-0,tuple<>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  30:     0x7ff6e3f2da2b - std::panic::{{impl}}::call_once<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,closure-0>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  31:     0x7ff6e3f44ee7 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  32:     0x7ff6e3f45843 - std::panicking::panicking
  33:     0x7ff6e3f4486f - std::panicking::try<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,std::panic::AssertUnwindSafe<closure-0>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  34:     0x7ff6e3f2de4b - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  35:     0x7ff6e3f3c190 - tokio::runtime::task::harness::Harness<alloc::boxed::Box<Future, alloc::alloc::Global>, alloc::sync::Arc<tokio::task::local::Shared>>::poll<alloc::boxed::Box<Future, alloc::alloc::Global>,alloc::sync::Arc<tokio::task::local::Shared>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\harness.rs:89
  36:     0x7ff6e3f1bdf2 - tokio::runtime::task::raw::poll<alloc::boxed::Box<Future, alloc::alloc::Global>,alloc::sync::Arc<tokio::task::local::Shared>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\raw.rs:104
  37:     0x7ff6e3fa7da0 - tokio::runtime::task::raw::RawTask::poll
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\raw.rs:66
  38:     0x7ff6e3f74477 - tokio::runtime::task::Notified<alloc::sync::Arc<tokio::task::local::Shared>>::run<alloc::sync::Arc<tokio::task::local::Shared>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\mod.rs:169
  39:     0x7ff6e3f796be - tokio::task::local::{{impl}}::tick::{{closure}}
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:408
  40:     0x7ff6e3fa0de7 - tokio::coop::with_budget::{{closure}}<tuple<>,closure-0>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:127
  41:     0x7ff6e3f96fa5 - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,tuple<>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:376
  42:     0x7ff6e3f95036 - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,tuple<>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:352
  43:     0x7ff6e3f79664 - tokio::coop::with_budget
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:120
  44:     0x7ff6e3f79664 - tokio::coop::budget
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:96
  45:     0x7ff6e3f79664 - tokio::task::local::LocalSet::tick
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:408
  46:     0x7ff6e3f33d48 - tokio::task::local::{{impl}}::poll::{{closure}}<futures_channel::oneshot::Receiver<i32>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:532
  47:     0x7ff6e3f1b4d1 - tokio::macros::scoped_tls::ScopedKey<tokio::task::local::Context>::set<tokio::task::local::Context,closure-0,core::task::poll::Poll<core::result::Result<i32, futures_channel::oneshot::Canceled>>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\macros\scoped_tls.rs:63
  48:     0x7ff6e3f3340a - tokio::task::local::LocalSet::with<core::task::poll::Poll<core::result::Result<i32, futures_channel::oneshot::Canceled>>,closure-0>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:442
  49:     0x7ff6e3f339c2 - tokio::task::local::{{impl}}::poll<futures_channel::oneshot::Receiver<i32>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:518
  50:     0x7ff6e3f33663 - tokio::task::local::{{impl}}::run_until::{{closure}}<futures_channel::oneshot::Receiver<i32>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:392
  51:     0x7ff6e3f31329 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
  52:     0x7ff6e3f302da - tokio::runtime::basic_scheduler::{{impl}}::block_on::{{closure}}::{{closure}}<tokio::park::either::Either<tokio::time::driver::Driver<tokio::park::either::Either<tokio::io::driver::Driver, tokio::park::thread::ParkThread>>, tokio::park::either::Either<tok
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:131
  53:     0x7ff6e3f2c159 - tokio::coop::with_budget::{{closure}}<core::task::poll::Poll<core::result::Result<i32, futures_channel::oneshot::Canceled>>,closure-0>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:127
  54:     0x7ff6e3f423c0 - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::task::poll::Poll<core::result::Result<i32, futures_channel::oneshot::Canceled>>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:376
  55:     0x7ff6e3f417cd - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::task::poll::Poll<core::result::Result<i32, futures_channel::oneshot::Canceled>>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:352
  56:     0x7ff6e3f2fc0e - tokio::coop::with_budget
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:120
  57:     0x7ff6e3f2fc0e - tokio::coop::budget
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:96
  58:     0x7ff6e3f2fc0e - tokio::runtime::basic_scheduler::{{impl}}::block_on::{{closure}}<tokio::park::either::Either<tokio::time::driver::Driver<tokio::park::either::Either<tokio::io::driver::Driver, tokio::park::thread::ParkThread>>, tokio::park::either::Either<tokio::io::drive
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:131
  59:     0x7ff6e3f30a8f - tokio::runtime::basic_scheduler::enter::{{closure}}<closure-0,core::result::Result<i32, futures_channel::oneshot::Canceled>,tokio::park::either::Either<tokio::time::driver::Driver<tokio::park::either::Either<tokio::io::driver::Driver, tokio::park::thread:
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:213
  60:     0x7ff6e3f1b3c1 - tokio::macros::scoped_tls::ScopedKey<tokio::runtime::basic_scheduler::Context>::set<tokio::runtime::basic_scheduler::Context,closure-0,core::result::Result<i32, futures_channel::oneshot::Canceled>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\macros\scoped_tls.rs:63
  61:     0x7ff6e3f308ad - tokio::runtime::basic_scheduler::enter<closure-0,core::result::Result<i32, futures_channel::oneshot::Canceled>,tokio::park::either::Either<tokio::time::driver::Driver<tokio::park::either::Either<tokio::io::driver::Driver, tokio::park::thread::ParkThread>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:213
  62:     0x7ff6e3f2f41d - tokio::runtime::basic_scheduler::BasicScheduler<tokio::park::either::Either<tokio::time::driver::Driver<tokio::park::either::Either<tokio::io::driver::Driver, tokio::park::thread::ParkThread>>, tokio::park::either::Either<tokio::io::driver::Driver, tokio:
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:123
  63:     0x7ff6e3f19d90 - tokio::runtime::{{impl}}::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\mod.rs:444
  64:     0x7ff6e3f27c29 - tokio::runtime::context::enter<closure-0,core::result::Result<i32, futures_channel::oneshot::Canceled>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\context.rs:72
  65:     0x7ff6e3f2cd92 - tokio::runtime::handle::Handle::enter<closure-0,core::result::Result<i32, futures_channel::oneshot::Canceled>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\handle.rs:76
  66:     0x7ff6e3f19b2a - tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\mod.rs:441
  67:     0x7ff6e3f334a7 - tokio::task::local::LocalSet::block_on<futures_channel::oneshot::Receiver<i32>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:353
  68:     0x7ff6e3f28e30 - actix_rt::runtime::Runtime::block_on<futures_channel::oneshot::Receiver<i32>>
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-1.1.1\src\runtime.rs:89
  69:     0x7ff6e3f23f7c - actix_rt::arbiter::{{impl}}::new::{{closure}}
                               at C:\Users\julia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-1.1.1\src\arbiter.rs:137
  70:     0x7ff6e3f12270 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,tuple<>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys_common\backtrace.rs:125
  71:     0x7ff6e3f31ee1 - std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,tuple<>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\mod.rs:481
  72:     0x7ff6e3f2d964 - std::panic::{{impl}}::call_once<tuple<>,closure-0>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  73:     0x7ff6e3f44bb1 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  74:     0x7ff6e3f45843 - std::panicking::panicking
  75:     0x7ff6e3f4426b - std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  76:     0x7ff6e3f2deb4 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  77:     0x7ff6e3f31d14 - std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-0,tuple<>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\mod.rs:480
  78:     0x7ff6e3f12e4e - core::ops::function::FnOnce::call_once<closure-0,tuple<>>
                               at C:\Users\julia\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  79:     0x7ff6e4079daa - alloc::boxed::{{impl}}::call_once
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\library\alloc\src\boxed.rs:1575
  80:     0x7ff6e4079daa - alloc::boxed::{{impl}}::call_once
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\library\alloc\src\boxed.rs:1575
  81:     0x7ff6e4079daa - std::sys::windows::thread::{{impl}}::new::thread_start
                               at /rustc/676ee14729462585b969bbc52f32c307403f4126\/library\std\src\sys\windows\thread.rs:56
  82:     0x7ffff6bc7034 - BaseThreadInitThunk
  83:     0x7ffff82a2651 - RtlUserThreadStart
```

**Comment by ryanmcgrath** [comment]
Huh, this one is interesting - I unfortunately don't know what could be causing this (i.e, if it's a Windows-specific issue).

What version of Rust are you using? The backtrace doesn't show anything from `jelly` to be causing it, so wondering if this is maybe an actix bug that's Windows-specific?

**Comment by JulianRuiseco** [comment]
After considerable investigation. I believe the issue is because my secret_key was insufficiently long.
